# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_test1(object):
    def setupUi(self, test1):
        test1.setObjectName("test1")
        test1.setEnabled(True)
        test1.resize(600, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(test1.sizePolicy().hasHeightForWidth())
        test1.setSizePolicy(sizePolicy)
        test1.setMinimumSize(QtCore.QSize(600, 560))
        test1.setMaximumSize(QtCore.QSize(600, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        test1.setWindowIcon(icon)
        test1.setAnimated(False)
        self.centralWidget = QtWidgets.QWidget(test1)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(19, 20, 561, 531))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_description = QtWidgets.QLabel(self.page_0)
        self.label_description.setGeometry(QtCore.QRect(50, 120, 451, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_description.sizePolicy().hasHeightForWidth())
        self.label_description.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_description.setFont(font)
        self.label_description.setToolTipDuration(-1)
        self.label_description.setAutoFillBackground(False)
        self.label_description.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_description.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_description.setLineWidth(1)
        self.label_description.setMidLineWidth(0)
        self.label_description.setTextFormat(QtCore.Qt.AutoText)
        self.label_description.setScaledContents(False)
        self.label_description.setWordWrap(False)
        self.label_description.setIndent(-1)
        self.label_description.setOpenExternalLinks(False)
        self.label_description.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.label_description.setObjectName("label_description")
        self.label_5 = QtWidgets.QLabel(self.page_0)
        self.label_5.setGeometry(QtCore.QRect(90, 260, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.page_0)
        self.label_4.setGeometry(QtCore.QRect(90, 340, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.page_0)
        self.label_6.setGeometry(QtCore.QRect(90, 300, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_0)
        self.label_7.setGeometry(QtCore.QRect(90, 380, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_0)
        self.label_8.setGeometry(QtCore.QRect(90, 420, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_1model = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_1model.setGeometry(QtCore.QRect(270, 260, 211, 31))
        self.lineEdit_1model.setObjectName("lineEdit_1model")
        self.lineEdit_2proc = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_2proc.setGeometry(QtCore.QRect(270, 300, 211, 31))
        self.lineEdit_2proc.setObjectName("lineEdit_2proc")
        self.lineEdit_3video = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_3video.setGeometry(QtCore.QRect(270, 340, 211, 31))
        self.lineEdit_3video.setObjectName("lineEdit_3video")
        self.lineEdit_4storage = QtWidgets.QLineEdit(self.page_0)
        self.lineEdit_4storage.setGeometry(QtCore.QRect(270, 380, 211, 31))
        self.lineEdit_4storage.setObjectName("lineEdit_4storage")
        self.dateEdit = QtWidgets.QDateEdit(self.page_0)
        self.dateEdit.setGeometry(QtCore.QRect(270, 420, 101, 31))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDateTime(QtCore.QDateTime.currentDateTime())
        self.btnArchive = QtWidgets.QPushButton(self.page_0)
        self.btnArchive.setGeometry(QtCore.QRect(380, 480, 101, 31))
        self.btnArchive.setObjectName("btnArchive")
        self.btnStart = QtWidgets.QPushButton(self.page_0)
        self.btnStart.setGeometry(QtCore.QRect(270, 480, 101, 31))
        self.btnStart.setObjectName("btnStart")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.btnPage1Prev = QtWidgets.QPushButton(self.page_1)
        self.btnPage1Prev.setGeometry(QtCore.QRect(10, 490, 80, 25))
        self.btnPage1Prev.setObjectName("btnPage1Prev")
        self.btnPage1Next = QtWidgets.QPushButton(self.page_1)
        self.btnPage1Next.setGeometry(QtCore.QRect(97, 490, 80, 25))
        self.btnPage1Next.setObjectName("btnPage1Next")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_1)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 40, 540, 430))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 539, 536))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox11.setObjectName("groupBox11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox11)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_11a = QtWidgets.QRadioButton(self.groupBox11)
        self.radioButton_11a.setObjectName("radioButton_11a")
        self.verticalLayout_2.addWidget(self.radioButton_11a)
        self.radioButton_11b = QtWidgets.QRadioButton(self.groupBox11)
        self.radioButton_11b.setObjectName("radioButton_11b")
        self.verticalLayout_2.addWidget(self.radioButton_11b)
        self.radioButton_11c = QtWidgets.QRadioButton(self.groupBox11)
        self.radioButton_11c.setObjectName("radioButton_11c")
        self.verticalLayout_2.addWidget(self.radioButton_11c)
        self.radioButton_11d = QtWidgets.QRadioButton(self.groupBox11)
        self.radioButton_11d.setObjectName("radioButton_11d")
        self.verticalLayout_2.addWidget(self.radioButton_11d)
        self.radioButton_11e = QtWidgets.QRadioButton(self.groupBox11)
        self.radioButton_11e.setObjectName("radioButton_11e")
        self.verticalLayout_2.addWidget(self.radioButton_11e)
        self.verticalLayout.addWidget(self.groupBox11)
        self.groupBox12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox12.setObjectName("groupBox12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox12)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.radioButton_12a = QtWidgets.QRadioButton(self.groupBox12)
        self.radioButton_12a.setObjectName("radioButton_12a")
        self.verticalLayout_15.addWidget(self.radioButton_12a)
        self.radioButton_12b = QtWidgets.QRadioButton(self.groupBox12)
        self.radioButton_12b.setObjectName("radioButton_12b")
        self.verticalLayout_15.addWidget(self.radioButton_12b)
        self.radioButton_12c = QtWidgets.QRadioButton(self.groupBox12)
        self.radioButton_12c.setObjectName("radioButton_12c")
        self.verticalLayout_15.addWidget(self.radioButton_12c)
        self.verticalLayout.addWidget(self.groupBox12)
        self.groupBox13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox13.setObjectName("groupBox13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox13)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.radioButton_13a = QtWidgets.QRadioButton(self.groupBox13)
        self.radioButton_13a.setObjectName("radioButton_13a")
        self.verticalLayout_16.addWidget(self.radioButton_13a)
        self.radioButton_13b = QtWidgets.QRadioButton(self.groupBox13)
        self.radioButton_13b.setObjectName("radioButton_13b")
        self.verticalLayout_16.addWidget(self.radioButton_13b)
        self.verticalLayout.addWidget(self.groupBox13)
        self.groupBox14 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox14.setObjectName("groupBox14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox14)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_14a = QtWidgets.QRadioButton(self.groupBox14)
        self.radioButton_14a.setObjectName("radioButton_14a")
        self.verticalLayout_3.addWidget(self.radioButton_14a)
        self.radioButton_14b = QtWidgets.QRadioButton(self.groupBox14)
        self.radioButton_14b.setObjectName("radioButton_14b")
        self.verticalLayout_3.addWidget(self.radioButton_14b)
        self.verticalLayout.addWidget(self.groupBox14)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 281, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnPage2Prev = QtWidgets.QPushButton(self.page_2)
        self.btnPage2Prev.setGeometry(QtCore.QRect(10, 490, 80, 25))
        self.btnPage2Prev.setObjectName("btnPage2Prev")
        self.btnPage2Next = QtWidgets.QPushButton(self.page_2)
        self.btnPage2Next.setGeometry(QtCore.QRect(97, 490, 80, 25))
        self.btnPage2Next.setObjectName("btnPage2Next")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 40, 540, 430))
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 527, 812))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox21 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox21.setObjectName("groupBox21")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox21)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.radioButton_21a = QtWidgets.QRadioButton(self.groupBox21)
        self.radioButton_21a.setObjectName("radioButton_21a")
        self.verticalLayout_18.addWidget(self.radioButton_21a)
        self.radioButton_21b = QtWidgets.QRadioButton(self.groupBox21)
        self.radioButton_21b.setObjectName("radioButton_21b")
        self.verticalLayout_18.addWidget(self.radioButton_21b)
        self.radioButton_21c = QtWidgets.QRadioButton(self.groupBox21)
        self.radioButton_21c.setObjectName("radioButton_21c")
        self.verticalLayout_18.addWidget(self.radioButton_21c)
        self.radioButton_21d = QtWidgets.QRadioButton(self.groupBox21)
        self.radioButton_21d.setObjectName("radioButton_21d")
        self.verticalLayout_18.addWidget(self.radioButton_21d)
        self.radioButton_21c.raise_()
        self.radioButton_21a.raise_()
        self.radioButton_21b.raise_()
        self.radioButton_21d.raise_()
        self.verticalLayout_17.addWidget(self.groupBox21)
        self.groupBox22 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox22.setObjectName("groupBox22")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox22)
        self.verticalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.radioButton_22a = QtWidgets.QRadioButton(self.groupBox22)
        self.radioButton_22a.setObjectName("radioButton_22a")
        self.verticalLayout_19.addWidget(self.radioButton_22a)
        self.radioButton_22b = QtWidgets.QRadioButton(self.groupBox22)
        self.radioButton_22b.setObjectName("radioButton_22b")
        self.verticalLayout_19.addWidget(self.radioButton_22b)
        self.radioButton_22c = QtWidgets.QRadioButton(self.groupBox22)
        self.radioButton_22c.setObjectName("radioButton_22c")
        self.verticalLayout_19.addWidget(self.radioButton_22c)
        self.verticalLayout_17.addWidget(self.groupBox22)
        self.groupBox23 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox23.setObjectName("groupBox23")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox23)
        self.verticalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.radioButton_23a = QtWidgets.QRadioButton(self.groupBox23)
        self.radioButton_23a.setObjectName("radioButton_23a")
        self.verticalLayout_20.addWidget(self.radioButton_23a)
        self.radioButton_23b = QtWidgets.QRadioButton(self.groupBox23)
        self.radioButton_23b.setObjectName("radioButton_23b")
        self.verticalLayout_20.addWidget(self.radioButton_23b)
        self.radioButton_23c = QtWidgets.QRadioButton(self.groupBox23)
        self.radioButton_23c.setObjectName("radioButton_23c")
        self.verticalLayout_20.addWidget(self.radioButton_23c)
        self.radioButton_23d = QtWidgets.QRadioButton(self.groupBox23)
        self.radioButton_23d.setObjectName("radioButton_23d")
        self.verticalLayout_20.addWidget(self.radioButton_23d)
        self.verticalLayout_17.addWidget(self.groupBox23)
        self.groupBox24 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox24.setObjectName("groupBox24")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox24)
        self.verticalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.radioButton_24a = QtWidgets.QRadioButton(self.groupBox24)
        self.radioButton_24a.setObjectName("radioButton_24a")
        self.verticalLayout_21.addWidget(self.radioButton_24a)
        self.radioButton_24b = QtWidgets.QRadioButton(self.groupBox24)
        self.radioButton_24b.setObjectName("radioButton_24b")
        self.verticalLayout_21.addWidget(self.radioButton_24b)
        self.radioButton_24c = QtWidgets.QRadioButton(self.groupBox24)
        self.radioButton_24c.setObjectName("radioButton_24c")
        self.verticalLayout_21.addWidget(self.radioButton_24c)
        self.radioButton_24d = QtWidgets.QRadioButton(self.groupBox24)
        self.radioButton_24d.setObjectName("radioButton_24d")
        self.verticalLayout_21.addWidget(self.radioButton_24d)
        self.verticalLayout_17.addWidget(self.groupBox24)
        self.groupBox25 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox25.setObjectName("groupBox25")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox25)
        self.verticalLayout_22.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.checkBox_25a = QtWidgets.QCheckBox(self.groupBox25)
        self.checkBox_25a.setObjectName("checkBox_25a")
        self.verticalLayout_22.addWidget(self.checkBox_25a)
        self.checkBox_25b = QtWidgets.QCheckBox(self.groupBox25)
        self.checkBox_25b.setObjectName("checkBox_25b")
        self.verticalLayout_22.addWidget(self.checkBox_25b)
        self.checkBox_25c = QtWidgets.QCheckBox(self.groupBox25)
        self.checkBox_25c.setObjectName("checkBox_25c")
        self.verticalLayout_22.addWidget(self.checkBox_25c)
        self.checkBox_25d = QtWidgets.QCheckBox(self.groupBox25)
        self.checkBox_25d.setObjectName("checkBox_25d")
        self.verticalLayout_22.addWidget(self.checkBox_25d)
        self.checkBox_25e = QtWidgets.QCheckBox(self.groupBox25)
        self.checkBox_25e.setObjectName("checkBox_25e")
        self.verticalLayout_22.addWidget(self.checkBox_25e)
        self.verticalLayout_17.addWidget(self.groupBox25)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 540, 430))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 524, 943))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox31 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox31.setObjectName("groupBox31")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox31)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_31a = QtWidgets.QCheckBox(self.groupBox31)
        self.checkBox_31a.setObjectName("checkBox_31a")
        self.verticalLayout_8.addWidget(self.checkBox_31a)
        self.checkBox_31b = QtWidgets.QCheckBox(self.groupBox31)
        self.checkBox_31b.setObjectName("checkBox_31b")
        self.verticalLayout_8.addWidget(self.checkBox_31b)
        self.checkBox_31c = QtWidgets.QCheckBox(self.groupBox31)
        self.checkBox_31c.setToolTip("")
        self.checkBox_31c.setObjectName("checkBox_31c")
        self.verticalLayout_8.addWidget(self.checkBox_31c)
        self.checkBox_31d = QtWidgets.QCheckBox(self.groupBox31)
        self.checkBox_31d.setObjectName("checkBox_31d")
        self.verticalLayout_8.addWidget(self.checkBox_31d)
        self.verticalLayout_12.addWidget(self.groupBox31)
        self.groupBox32 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox32.setObjectName("groupBox32")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox32)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_32a = QtWidgets.QCheckBox(self.groupBox32)
        self.checkBox_32a.setObjectName("checkBox_32a")
        self.verticalLayout_9.addWidget(self.checkBox_32a)
        self.checkBox_32b = QtWidgets.QCheckBox(self.groupBox32)
        self.checkBox_32b.setObjectName("checkBox_32b")
        self.verticalLayout_9.addWidget(self.checkBox_32b)
        self.checkBox_32c = QtWidgets.QCheckBox(self.groupBox32)
        self.checkBox_32c.setObjectName("checkBox_32c")
        self.verticalLayout_9.addWidget(self.checkBox_32c)
        self.checkBox_32d = QtWidgets.QCheckBox(self.groupBox32)
        self.checkBox_32d.setObjectName("checkBox_32d")
        self.verticalLayout_9.addWidget(self.checkBox_32d)
        self.verticalLayout_12.addWidget(self.groupBox32)
        self.groupBox33 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox33.setObjectName("groupBox33")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox33)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_33a = QtWidgets.QCheckBox(self.groupBox33)
        self.checkBox_33a.setObjectName("checkBox_33a")
        self.verticalLayout_10.addWidget(self.checkBox_33a)
        self.checkBox_33b = QtWidgets.QCheckBox(self.groupBox33)
        self.checkBox_33b.setObjectName("checkBox_33b")
        self.verticalLayout_10.addWidget(self.checkBox_33b)
        self.checkBox_33c = QtWidgets.QCheckBox(self.groupBox33)
        self.checkBox_33c.setObjectName("checkBox_33c")
        self.verticalLayout_10.addWidget(self.checkBox_33c)
        self.verticalLayout_12.addWidget(self.groupBox33)
        self.groupBox34 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox34.setObjectName("groupBox34")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox34)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.checkBox_34a = QtWidgets.QCheckBox(self.groupBox34)
        self.checkBox_34a.setObjectName("checkBox_34a")
        self.verticalLayout_14.addWidget(self.checkBox_34a)
        self.checkBox_34b = QtWidgets.QCheckBox(self.groupBox34)
        self.checkBox_34b.setObjectName("checkBox_34b")
        self.verticalLayout_14.addWidget(self.checkBox_34b)
        self.checkBox_34c = QtWidgets.QCheckBox(self.groupBox34)
        self.checkBox_34c.setObjectName("checkBox_34c")
        self.verticalLayout_14.addWidget(self.checkBox_34c)
        self.checkBox_34d = QtWidgets.QCheckBox(self.groupBox34)
        self.checkBox_34d.setObjectName("checkBox_34d")
        self.verticalLayout_14.addWidget(self.checkBox_34d)
        self.verticalLayout_12.addWidget(self.groupBox34)
        self.groupBox35 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox35.setObjectName("groupBox35")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox35)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_35a = QtWidgets.QCheckBox(self.groupBox35)
        self.checkBox_35a.setObjectName("checkBox_35a")
        self.verticalLayout_13.addWidget(self.checkBox_35a)
        self.checkBox_35b = QtWidgets.QCheckBox(self.groupBox35)
        self.checkBox_35b.setObjectName("checkBox_35b")
        self.verticalLayout_13.addWidget(self.checkBox_35b)
        self.checkBox_35c = QtWidgets.QCheckBox(self.groupBox35)
        self.checkBox_35c.setObjectName("checkBox_35c")
        self.verticalLayout_13.addWidget(self.checkBox_35c)
        self.checkBox_35d = QtWidgets.QCheckBox(self.groupBox35)
        self.checkBox_35d.setObjectName("checkBox_35d")
        self.verticalLayout_13.addWidget(self.checkBox_35d)
        self.verticalLayout_12.addWidget(self.groupBox35)
        self.groupBox36 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox36.setObjectName("groupBox36")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox36)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_36a = QtWidgets.QCheckBox(self.groupBox36)
        self.checkBox_36a.setObjectName("checkBox_36a")
        self.verticalLayout_11.addWidget(self.checkBox_36a)
        self.checkBox_36b = QtWidgets.QCheckBox(self.groupBox36)
        self.checkBox_36b.setObjectName("checkBox_36b")
        self.verticalLayout_11.addWidget(self.checkBox_36b)
        self.checkBox_36c = QtWidgets.QCheckBox(self.groupBox36)
        self.checkBox_36c.setObjectName("checkBox_36c")
        self.verticalLayout_11.addWidget(self.checkBox_36c)
        self.checkBox_36d = QtWidgets.QCheckBox(self.groupBox36)
        self.checkBox_36d.setObjectName("checkBox_36d")
        self.verticalLayout_11.addWidget(self.checkBox_36d)
        self.verticalLayout_12.addWidget(self.groupBox36)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnPage3Prev = QtWidgets.QPushButton(self.page_3)
        self.btnPage3Prev.setGeometry(QtCore.QRect(10, 490, 80, 25))
        self.btnPage3Prev.setObjectName("btnPage3Prev")
        self.btnPage3Next = QtWidgets.QPushButton(self.page_3)
        self.btnPage3Next.setGeometry(QtCore.QRect(97, 490, 80, 25))
        self.btnPage3Next.setObjectName("btnPage3Next")
        self.stackedWidget.addWidget(self.page_3)
        test1.setCentralWidget(self.centralWidget)

        self.retranslateUi(test1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(test1)

    def retranslateUi(self, test1):
        _translate = QtCore.QCoreApplication.translate
        test1.setWindowTitle(_translate("test1", "Экспертная система"))
        self.label_description.setText(_translate("test1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Диагностическая экспертная система определения</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">неисправностей персонального компьютера </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">и пути их решения</span></p></body></html>"))
        self.label_5.setText(_translate("test1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Материнская плата </p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(или модель ноутбука):</p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("test1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Видеокарта:</span></p></body></html>"))
        self.label_6.setText(_translate("test1", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Процессор:</span></p></body></html>"))
        self.label_7.setText(_translate("test1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Хранилище данных:</span></p></body></html>"))
        self.label_8.setText(_translate("test1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Дата диагностики:</span></p></body></html>"))
        self.btnArchive.setText(_translate("test1", "Архив"))
        self.btnStart.setText(_translate("test1", "Начать"))
        self.label.setText(_translate("test1", "<html><head/><body><p>Аппаратная часть</p></body></html>"))
        self.btnPage1Prev.setText(_translate("test1", "Назад"))
        self.btnPage1Next.setText(_translate("test1", "Далее"))
        self.groupBox11.setTitle(_translate("test1", "1.1. Процесс включения изменился, есть отличия от последней успешной загрузки"))
        self.radioButton_11a.setText(_translate("test1", "Нет. Компьютер включается так же, как и раньше"))
        self.radioButton_11b.setText(_translate("test1", "Нет. Но компьютер включается дольше"))
        self.radioButton_11c.setText(_translate("test1", "Да. При включении издает один или несколько сигналов(раньше нет)"))
        self.radioButton_11d.setText(_translate("test1", "Да. Включение остановилось, на экране несколько надписей"))
        self.radioButton_11e.setText(_translate("test1", "Да. Компьютер бесконечно перезагружается"))
        self.groupBox12.setTitle(_translate("test1", "1.2. Область корпуса или ноутбука греется"))
        self.radioButton_12a.setText(_translate("test1", "Да, но только при большой нагрузке"))
        self.radioButton_12b.setText(_translate("test1", "Да, при любой нагрузке"))
        self.radioButton_12c.setText(_translate("test1", "Нет"))
        self.groupBox13.setTitle(_translate("test1", "1.3. Неестественный звук при работе аппартного обеспечения"))
        self.radioButton_13a.setText(_translate("test1", "Да"))
        self.radioButton_13b.setText(_translate("test1", "Нет"))
        self.groupBox14.setTitle(_translate("test1", "1.4. Корпус системного блока (ноутбука) или разъемы бьются током"))
        self.radioButton_14a.setText(_translate("test1", "Да"))
        self.radioButton_14b.setText(_translate("test1", "Нет"))
        self.label_2.setText(_translate("test1", "Устройства компьютера"))
        self.btnPage2Prev.setText(_translate("test1", "Назад"))
        self.btnPage2Next.setText(_translate("test1", "Далее"))
        self.groupBox21.setTitle(_translate("test1", "2.1. Работа экрана изменилась?"))
        self.radioButton_21a.setText(_translate("test1", "Нет. Экран работает так же"))
        self.radioButton_21b.setText(_translate("test1", "Да. Изображение стало менее четким, расплывчатым"))
        self.radioButton_21c.setText(_translate("test1", "Да. Экран включается, но изображение мерцает"))
        self.radioButton_21d.setText(_translate("test1", "Да. На экране появились черные (или белые) статические точки (пятна)"))
        self.groupBox22.setTitle(_translate("test1", "2.2. Работа звука (звуковой карты)"))
        self.radioButton_22a.setText(_translate("test1", "Звук работает так же"))
        self.radioButton_22b.setText(_translate("test1", "Звук есть, но он изменился (непроизвольные откючение, свист, искажение)"))
        self.radioButton_22c.setText(_translate("test1", "Звук отсутствует"))
        self.groupBox23.setTitle(_translate("test1", "2.3. Работа LAN, WI-FI"))
        self.radioButton_23a.setText(_translate("test1", "Интернет есть, подлкючение стабильное"))
        self.radioButton_23b.setText(_translate("test1", "Интернет есть, но WI-FI работает с перебоями (непроизвольное отключение)"))
        self.radioButton_23c.setText(_translate("test1", "Интернет есть, WI-FI не работает"))
        self.radioButton_23d.setText(_translate("test1", "Интернет есть, LAN не работает"))
        self.groupBox24.setTitle(_translate("test1", "2.4. Работа USB-портов"))
        self.radioButton_24a.setText(_translate("test1", "Порты работают стабильно, все устройства определяются"))
        self.radioButton_24b.setText(_translate("test1", "Некоторые устройства не определяются"))
        self.radioButton_24c.setText(_translate("test1", "Порты на передней панели системного блока не работают"))
        self.radioButton_24d.setText(_translate("test1", "Порты на одной из сторон ноутбука не работают"))
        self.groupBox25.setTitle(_translate("test1", "2.5. Работа периферийных устройств"))
        self.checkBox_25a.setText(_translate("test1", "Все устройства работают исправно"))
        self.checkBox_25b.setText(_translate("test1", "Мышь не работает"))
        self.checkBox_25c.setText(_translate("test1", "Тачпад не работает"))
        self.checkBox_25d.setText(_translate("test1", "Клавиатура не работает"))
        self.checkBox_25e.setText(_translate("test1", "Камера не работает"))
        self.label_3.setText(_translate("test1", "Операционная система"))
        self.groupBox31.setTitle(_translate("test1", "3.1. Работа операционной системы (ОС)"))
        self.checkBox_31a.setText(_translate("test1", "Работа ОС стабильна"))
        self.checkBox_31b.setText(_translate("test1", "ОС долго загружается"))
        self.checkBox_31c.setText(_translate("test1", "При загрузке ОС появляется критическая ошибка (BSOD)"))
        self.checkBox_31d.setText(_translate("test1", "Экран заблокирован, с просьбой выслать деньги по указаному номеру"))
        self.groupBox32.setTitle(_translate("test1", "3.2. Работа программного обеспечения (ПО)"))
        self.checkBox_32a.setText(_translate("test1", "Всё ПО работает стабильно"))
        self.checkBox_32b.setText(_translate("test1", "Некоторые программы аварийно завершают свою работу"))
        self.checkBox_32c.setText(_translate("test1", "Некоторые программы замедляют работу ОС"))
        self.checkBox_32d.setText(_translate("test1", "Программа не запускается"))
        self.groupBox33.setTitle(_translate("test1", "3.3. Работа видео"))
        self.checkBox_33a.setText(_translate("test1", "Видео тормозит"))
        self.checkBox_33b.setText(_translate("test1", "Видео не воспроизводится"))
        self.checkBox_33c.setText(_translate("test1", "Видео работает стабильно (любое разрешение)"))
        self.groupBox34.setTitle(_translate("test1", "3.4. Работа игр"))
        self.checkBox_34a.setText(_translate("test1", "Компьютер греется во время игр"))
        self.checkBox_34b.setText(_translate("test1", "Во время игры происходит искажение видео"))
        self.checkBox_34c.setText(_translate("test1", "Нетребовательные игры работают стабильно"))
        self.checkBox_34d.setText(_translate("test1", "Игры с высокими системными требования работают с замедлениями"))
        self.groupBox35.setTitle(_translate("test1", "3.5. Обновление ОС"))
        self.checkBox_35a.setText(_translate("test1", "Работа ОС стабильна"))
        self.checkBox_35b.setText(_translate("test1", "Работа ОС стала хуже"))
        self.checkBox_35c.setText(_translate("test1", "Работа некоторых компонентов стала хуже"))
        self.checkBox_35d.setText(_translate("test1", "Работа периферийных устройств ухудшилась (или вообще не работают)"))
        self.groupBox36.setTitle(_translate("test1", "3.6. Файлы"))
        self.checkBox_36a.setText(_translate("test1", "Все файлы открываются нормально"))
        self.checkBox_36b.setText(_translate("test1", "Некоторые файлы не октрываются (Ошибка: Нет прав администратора)"))
        self.checkBox_36c.setText(_translate("test1", "Некоторые файлы не открываются (Ошибка: Содержимое повреждено)"))
        self.checkBox_36d.setText(_translate("test1", "Содержимое файлов имеет вид, неудобный для чтения"))
        self.btnPage3Prev.setText(_translate("test1", "Назад"))
        self.btnPage3Next.setText(_translate("test1", "Далее"))

